INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(MSGPACK_INCLUDE_DIR msgpack.h HINTS $ENV{MSGPACK_DIR})
FIND_LIBRARY(MSGPACK_LIBRARIES msgpackc HINTS $ENV{MSGPACK_DIR})
MARK_AS_ADVANCED(MSGPACK_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  MessagePack
  DEFAULT_MSG
  MSGPACK_LIBRARIES
  MSGPACK_INCLUDE_DIR
)

