INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(FLUIDSYNTH_INCLUDE_DIR fluidsynth.h HINTS $ENV{FLUIDSYNTH_DIR})
FIND_LIBRARY(FLUIDSYNTH_LIBRARIES fluidsynth HINTS $ENV{FLUIDSYNTH_DIR})
MARK_AS_ADVANCED(FLUIDSYNTH_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  FluidSynth
  DEFAULT_MSG
  FLUIDSYNTH_LIBRARIES
  FLUIDSYNTH_INCLUDE_DIR
)

