INCLUDE(FindPackageHandleStandardArgs)

IF (NOT GPERF_LIBRARIES)
    FIND_LIBRARY(GPERF_LIBRARIES profiler HINTS $ENV{GPERF_DIR})
ENDIF()

MARK_AS_ADVANCED(GPERF_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    GPerf
    DEFAULT_MSG
    GPERF_LIBRARIES
)

