INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(DUMB_INCLUDE_DIR dumb.h HINTS $ENV{DUMB_DIR})
FIND_LIBRARY(DUMB_LIBRARY dumb HINTS $ENV{DUMB_DIR})
MARK_AS_ADVANCED(DUMB_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Dumb
  REQUIRED_VARS
  DUMB_LIBRARY
  DUMB_INCLUDE_DIR
)

