INCLUDE(FindPackageHandleStandardArgs)

IF (NOT FREETYPE_INCLUDE_DIR)
    FIND_PATH(FREETYPE_INCLUDE_DIR freetype2/freetype.h
              HINTS $ENV{FREETYPE_DIR})
ENDIF()
IF (NOT FREETYPE_LIBRARIES)
    FIND_LIBRARY(FREETYPE_LIBRARIES freetype HINTS $ENV{FREETYPE_DIR})
ENDIF()

MARK_AS_ADVANCED(FREETYPE_INCLUDE_DIR)
MARK_AS_ADVANCED(FREETYPE_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    FreeType
    DEFAULT_MSG
    FREETYPE_LIBRARIES
    FREETYPE_INCLUDE_DIR
)

