INCLUDE(FindPackageHandleStandardArgs)

IF (NOT OGG_INCLUDE_DIR)
    FIND_PATH(OGG_INCLUDE_DIR ogg/ogg.h HINTS $ENV{OGG_DIR})
ENDIF()

IF (NOT OGG_LIBRARIES)
    FIND_LIBRARY(OGG_LIBRARIES ogg HINTS $ENV{OGG_DIR})
ENDIF()

MARK_AS_ADVANCED(OGG_INCLUDE_DIR)
MARK_AS_ADVANCED(OGG_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    Ogg
    DEFAULT_MSG
    OGG_LIBRARIES
    OGG_INCLUDE_DIR
)

