INCLUDE(FindPackageHandleStandardArgs)

IF (NOT LZMA_INCLUDE_DIR)
    FIND_PATH(LZMA_INCLUDE_DIR lzma.h HINTS $ENV{LZMA_DIR})
ENDIF()

IF (NOT LZMA_LIBRARIES)
    FIND_LIBRARY(LZMA_LIBRARIES lzma HINTS $ENV{LZMA_DIR})
ENDIF()

MARK_AS_ADVANCED(LZMA_INCLUDE_DIR)
MARK_AS_ADVANCED(LZMA_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
   LZMA
   DEFAULT_MSG
   LZMA_LIBRARIES
   LZMA_INCLUDE_DIR
)

