INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(PNG_INCLUDE_DIR png.h HINTS $ENV{PNG_DIR})
FIND_LIBRARY(PNG_LIBRARY png HINTS $ENV{PNG_DIR})
MARK_AS_ADVANCED(PNG_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  PNG
  REQUIRED_VARS
  PNG_LIBRARY
  PNG_INCLUDE_DIR
)

