INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(ENET_INCLUDE_DIR enet/enet.h HINTS $ENV{ENET_DIR})
FIND_LIBRARY(ENET_LIBRARIES enet HINTS $ENV{ENET_DIR})
MARK_AS_ADVANCED(ENET_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  ENet
  DEFAULT_MSG
  ENET_LIBRARIES
  ENET_INCLUDE_DIR
)

