INCLUDE(FindPackageHandleStandardArgs)

IF (NOT TIFF_INCLUDE_DIR)
    FIND_PATH(TIFF_INCLUDE_DIR tiff.h HINTS $ENV{TIFF_DIR})
ENDIF()
IF (NOT TIFF_LIBRARIES)
    FIND_LIBRARY(TIFF_LIBRARIES tiff HINTS $ENV{TIFF_DIR})
ENDIF()

MARK_AS_ADVANCED(TIFF_INCLUDE_DIR)
MARK_AS_ADVANCED(TIFF_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    TIFF
    DEFAULT_MSG
    TIFF_LIBRARIES
    TIFF_INCLUDE_DIR
)

