INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(MAD_INCLUDE_DIR mad.h HINTS $ENV{MAD_DIR})
FIND_LIBRARY(MAD_LIBRARIES mad HINTS $ENV{MAD_DIR})
MARK_AS_ADVANCED(MAD_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Mad
  DEFAULT_MSG
  MAD_LIBRARIES
  MAD_INCLUDE_DIR
)

