INCLUDE(FindPackageHandleStandardArgs)

# FIND_PACKAGE(PkgConfig)
# PKG_CHECK_MODULES(PC_CURL QUIET curl)

IF (NOT CURL_INCLUDE_DIR)
    FIND_PATH(CURL_INCLUDE_DIR curl.h
        HINTS $ENV{CURL_DIR} ${PC_CURL_INCLUDEDIR} ${PC_CURL_INCLUDE_DIRS}
        PATH_SUFFIXES curl
    )
ENDIF()
IF (NOT CURL_LIBRARIES)
    FIND_LIBRARY(CURL_LIBRARIES curl HINTS $ENV{CURL_DIR})
ENDIF()

MARK_AS_ADVANCED(CURL_INCLUDE_DIR)
MARK_AS_ADVANCED(CURL_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    cURL
    DEFAULT_MSG
    CURL_LIBRARIES
    CURL_INCLUDE_DIR
)

