INCLUDE(FindPackageHandleStandardArgs)

IF (NOT MIKMOD_INCLUDE_DIR)
    FIND_PATH(MIKMOD_INCLUDE_DIR mikmod.h HINTS $ENV{MIKMOD_DIR})
ENDIF()

IF (NOT MIKMOD_LIBRARIES)
    FIND_LIBRARY(MIKMOD_LIBRARIES mikmod HINTS $ENV{MIKMOD_DIR})
ENDIF()

MARK_AS_ADVANCED(MIKMOD_INCLUDE_DIR)
MARK_AS_ADVANCED(MIKMOD_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    MikMod
    DEFAULT_MSG
    MIKMOD_LIBRARIES
    MIKMOD_INCLUDE_DIR
)

