INCLUDE(FindPackageHandleStandardArgs)

IF (NOT XDIFF_INCLUDE_DIR)
    FIND_PATH(XDIFF_INCLUDE_DIR xdiff.h HINTS $ENV{XDIFF_DIR})
ENDIF()

IF (NOT XDIFF_LIBRARIES)
    FIND_LIBRARY(XDIFF_LIBRARIES xdiff HINTS $ENV{XDIFF_DIR})
ENDIF()

MARK_AS_ADVANCED(XDIFF_INCLUDE_DIR)
MARK_AS_ADVANCED(XDIFF_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    XDiff
    DEFAULT_MSG
    XDIFF_LIBRARIES
    XDIFF_INCLUDE_DIR
)

