INCLUDE(FindPackageHandleStandardArgs)

IF (NOT WEBP_INCLUDE_DIR)
    FIND_PATH(WEBP_INCLUDE_DIR webp/encode.h HINTS $ENV{WEBP_DIR})
ENDIF()

IF (NOT WEBP_LIBRARY)
    FIND_LIBRARY(WEBP_LIBRARIES webp HINTS $ENV{WEBP_DIR})
ENDIF()

MARK_AS_ADVANCED(WEBP_INCLUDE_DIR)
MARK_AS_ADVANCED(WEBP_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    WEBP
    DEFAULT_MSG
    WEBP_LIBRARIES
    WEBP_INCLUDE_DIR
)

