INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(VORBIS_INCLUDE_DIR vorbis/vorbisfile.h HINTS $ENV{VORBIS_DIR})
FIND_LIBRARY(VORBIS_LIBRARY vorbis HINTS $ENV{VORBIS_DIR})
MARK_AS_ADVANCED(VORBIS_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Vorbis
  REQUIRED_VARS
  VORBIS_LIBRARY
  VORBIS_INCLUDE_DIR
)

