INCLUDE(FindPkgConfig)
INCLUDE(FindPackageHandleStandardArgs)

PKG_SEARCH_MODULE(PkgConfig_FFI libffi)

IF (NOT FFI_INCLUDE_DIR)
    FIND_PATH(FFI_INCLUDE_DIR ffi.h
        HINTS $ENV{FFI_DIR} ${PkgConfig_FFI_INCLUDE_DIRS}
    )
ENDIF()
IF (NOT FFI_LIBRARIES)
    FIND_LIBRARY(FFI_LIBRARIES ffi HINTS $ENV{FFI_DIR})
ENDIF()

MARK_AS_ADVANCED(FFI_INCLUDE_DIR)
MARK_AS_ADVANCED(FFI_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    FFI
    DEFAULT_MSG
    FFI_LIBRARIES
    FFI_INCLUDE_DIR
)

