INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(XDIFF_INCLUDE_DIR xdiff.h HINTS $ENV{XDIFF_DIR})
FIND_LIBRARY(XDIFF_LIBRARIES xdiff HINTS $ENV{XDIFF_DIR})
MARK_AS_ADVANCED(XDIFF_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  XDiff
  DEFAULT_MSG
  XDIFF_LIBRARIES
  XDIFF_INCLUDE_DIR
)

