INCLUDE(FindPackageHandleStandardArgs)

IF (NOT READLINE_INCLUDE_DIR)
    FIND_PATH(READLINE_INCLUDE_DIR readline/readline.h HINTS $ENV{READLINE_DIR})
ENDIF()

IF (NOT READLINE_LIBRARY)
    FIND_LIBRARY(READLINE_LIBRARY readline HINTS $ENV{READLINE_DIR})
ENDIF()

IF (NOT HISTORY_LIBRARY)
    FIND_LIBRARY(HISTORY_LIBRARY history HINTS $ENV{READLINE_DIR})
ENDIF()

if (NOT READLINE_LIBRARIES)
    SET(READLINE_LIBRARIES ${READLINE_LIBRARY} ${HISTORY_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(READLINE_INCLUDE_DIR)
MARK_AS_ADVANCED(READLINE_LIBRARY)
MARK_AS_ADVANCED(HISTORY_LIBRARY)
MARK_AS_ADVANCED(READLINE_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    Readline
    DEFAULT_MSG
    READLINE_LIBRARIES
    READLINE_INCLUDE_DIR
)

