INCLUDE(FindPackageHandleStandardArgs)

IF (NOT GLIB_INCLUDE_DIR)
    FIND_PATH(GLIB_INCLUDE_DIR glib-2.0/glib.h HINTS $ENV{GLIB_DIR})
ENDIF()

IF (NOT GLIB_LIBRARIES)
    IF (NOT GMODULE_LIBRARY)
        FIND_LIBRARY(GMODULE_LIBRARY gmodule-2.0 HINTS $ENV{GLIB_DIR})
    ENDIF()

    IF (NOT GOBJECT_LIBRARY)
        FIND_LIBRARY(GOBJECT_LIBRARY gobject-2.0 HINTS $ENV{GLIB_DIR})
    ENDIF()

    IF (NOT GTHREAD_LIBRARY)
        FIND_LIBRARY(GTHREAD_LIBRARY gthread-2.0 HINTS $ENV{GLIB_DIR})
    ENDIF()

    IF (NOT GLIB_LIBRARY)
        FIND_LIBRARY(GLIB_LIBRARY glib-2.0 HINTS $ENV{GLIB_DIR})
    ENDIF()

    IF (GMODULE_LIBRARY AND GOBJECT_LIBRARY AND GTHREAD_LIBRARY
                        AND GLIB_LIBRARY)
        SET(GLIB_LIBRARIES ${GMODULE_LIBRARY} ${GOBJECT_LIBRARY} ${GTHREAD_LIBRARY}
                           ${GLIB_LIBRARY})
    ENDIF()
ENDIF()

MARK_AS_ADVANCED(GLIB_INCLUDE_DIR)
MARK_AS_ADVANCED(GMODULE_LIBRARY)
MARK_AS_ADVANCED(GOBJECT_LIBRARY)
MARK_AS_ADVANCED(GTHREAD_LIBRARY)
MARK_AS_ADVANCED(GLIB_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    GLib
    DEFAULT_MSG
    GLIB_LIBRARIES
    GLIB_INCLUDE_DIR
)

