INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(MAD_INCLUDE_DIR mad.h HINTS $ENV{MAD_DIR})
FIND_LIBRARY(MAD_LIBRARY mad HINTS $ENV{MAD_DIR})
MARK_AS_ADVANCED(MAD_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Mad
  REQUIRED_VARS
  MAD_LIBRARY
  MAD_INCLUDE_DIR
)

