INCLUDE(FindPackageHandleStandardArgs)

IF (NOT HARFBUZZ_INCLUDE_DIR)
    FIND_PATH(HARFBUZZ_INCLUDE_DIR harfbuzz/hb.h HINTS $ENV{HARFBUZZ_DIR})
ENDIF()
IF (NOT HARFBUZZ_LIBRARIES)
    FIND_LIBRARY(HARFBUZZ_LIBRARIES harfbuzz HINTS $ENV{HARFBUZZ_DIR})
ENDIF()

MARK_AS_ADVANCED(HARFBUZZ_INCLUDE_DIR)
MARK_AS_ADVANCED(HARFBUZZ_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    HarfBuzz
    DEFAULT_MSG
    HARFBUZZ_LIBRARIES
    HARFBUZZ_INCLUDE_DIR
)

