INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(PORTMIDI_INCLUDE_DIR portmidi.h HINTS $ENV{PORTMIDI_DIR})
FIND_LIBRARY(PORTMIDI_LIBRARY portmidi HINTS $ENV{PORTMIDI_DIR})
FIND_LIBRARY(PORTTIME_LIBRARY porttime HINTS $ENV{PORTMIDI_DIR})

SET(PORTMIDI_LIBRARIES ${PORTMIDI_LIBRARY} ${PORTTIME_LIBRARY})
MARK_AS_ADVANCED(PORTMIDI_LIBRARY)
MARK_AS_ADVANCED(PORTTIME_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  PortMidi
  DEFAULT_MSG
  PORTMIDI_INCLUDE_DIR
  PORTMIDI_LIBRARIES
)

