INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(PORTMIDI_INCLUDE_DIR portmidi.h HINTS $ENV{PORTMIDI_DIR})
FIND_LIBRARY(PORTMIDI_LIBRARY_LIB portmidi HINTS $ENV{PORTMIDI_DIR})
FIND_LIBRARY(PORTTIME_LIBRARY_LIB porttime HINTS $ENV{PORTMIDI_DIR})

IF (PORTMIDI_LIBRARY_LIB AND PORTTIME_LIBRARY_LIB)
  SET(PORTMIDI_LIBRARIES ${PORTMIDI_LIBRARY_LIB} ${PORTTIME_LIBRARY_LIB})
ENDIF()

MARK_AS_ADVANCED(PORTMIDI_LIBRARY)
MARK_AS_ADVANCED(PORTTIME_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  PortMidi
  DEFAULT_MSG
  PORTMIDI_LIBRARIES
  PORTMIDI_INCLUDE_DIR
)

