INCLUDE(FindPackageHandleStandardArgs)

IF (NOT PNG_INCLUDE_DIR)
    FIND_PATH(PNG_INCLUDE_DIR png.h HINTS $ENV{PNG_DIR})
ENDIF()

IF (NOT PNG_LIBRARIES)
    FIND_LIBRARY(PNG_LIBRARIES png HINTS $ENV{PNG_DIR})
ENDIF()

MARK_AS_ADVANCED(PNG_INCLUDE_DIR)
MARK_AS_ADVANCED(PNG_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    PNG
    DEFAULT_MSG
    PNG_LIBRARIES
    PNG_INCLUDE_DIR
)

