INCLUDE(FindPackageHandleStandardArgs)

IF (NOT JPG_INCLUDE_DIR)
    FIND_PATH(JPG_INCLUDE_DIR jpeglib.h HINTS $ENV{JPG_DIR})
ENDIF()

IF (NOT JPG_LIBRARIES)
    FIND_LIBRARY(JPG_LIBRARIES jpeg HINTS $ENV{JPG_DIR})
ENDIF()

MARK_AS_ADVANCED(JPG_INCLUDE_DIR)
MARK_AS_ADVANCED(JPG_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    JPG
    DEFAULT_MSG
    JPG_LIBRARIES
    JPG_INCLUDE_DIR
)

