INCLUDE(FindPackageHandleStandardArgs)

IF (NOT CAIRO_INCLUDE_DIR)
    FIND_PATH(CAIRO_INCLUDE_DIR cairo/cairo.h HINTS $ENV{CAIRO_DIR})
ENDIF()
IF (NOT CAIRO_LIBRARIES)
    FIND_LIBRARY(CAIRO_LIBRARIES cairo HINTS $ENV{CAIRO_DIR})
ENDIF()

MARK_AS_ADVANCED(CAIRO_INCLUDE_DIR)
MARK_AS_ADVANCED(CAIRO_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    Cairo
    DEFAULT_MSG
    CAIRO_LIBRARIES
    CAIRO_INCLUDE_DIR
)

