INCLUDE(FindPackageHandleStandardArgs)

IF (NOT FLUIDSYNTH_INCLUDE_DIR)
    FIND_PATH(FLUIDSYNTH_INCLUDE_DIR fluidsynth.h HINTS $ENV{FLUIDSYNTH_DIR})
ENDIF()

IF (NOT FLUIDSYNTH_LIBRARIES)
    FIND_LIBRARY(FLUIDSYNTH_LIBRARIES fluidsynth HINTS $ENV{FLUIDSYNTH_DIR})
ENDIF()

MARK_AS_ADVANCED(FLUIDSYNTH_INCLUDE_DIR)
MARK_AS_ADVANCED(FLUIDSYNTH_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    FluidSynth
    DEFAULT_MSG
    FLUIDSYNTH_LIBRARIES
    FLUIDSYNTH_INCLUDE_DIR
)

