INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(GPERF_LIBRARIES profiler HINTS $ENV{GPERF_DIR})
MARK_AS_ADVANCED(GPERF_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  GPerf
  DEFAULT_MSG
  GPERF_LIBRARIES
)

