INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(PCRE_INCLUDE_DIR pcre.h HINTS $ENV{PCRE_DIR})
FIND_LIBRARY(PCRE_LIBRARIES pcreposix HINTS $ENV{PCRE_DIR})
MARK_AS_ADVANCED(PCRE_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  PCRE
  DEFAULT_MSG
  PCRE_LIBRARIES
  PCRE_INCLUDE_DIR
)

