INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(DUMB_INCLUDE_DIR dumb.h HINTS $ENV{DUMB_DIR})
FIND_LIBRARY(DUMB_LIBRARIES dumb HINTS $ENV{DUMB_DIR})
MARK_AS_ADVANCED(DUMB_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Dumb
  DEFAULT_MSG
  DUMB_LIBRARIES
  DUMB_INCLUDE_DIR
)

