INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(OGG_INCLUDE_DIR ogg/ogg.h HINTS $ENV{OGG_DIR})
FIND_LIBRARY(OGG_LIBRARIES ogg HINTS $ENV{OGG_DIR})
MARK_AS_ADVANCED(OGG_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  Ogg
  DEFAULT_MSG
  OGG_LIBRARIES
  OGG_INCLUDE_DIR
)

