INCLUDE(FindPackageHandleStandardArgs)

IF (NOT DUMB_INCLUDE_DIR)
    FIND_PATH(DUMB_INCLUDE_DIR dumb.h HINTS $ENV{DUMB_DIR})
ENDIF()

IF (NOT DUMB_LIBRARIES)
    FIND_LIBRARY(DUMB_LIBRARIES dumb HINTS $ENV{DUMB_DIR})
ENDIF()

MARK_AS_ADVANCED(DUMB_INCLUDE_DIR)
MARK_AS_ADVANCED(DUMB_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    Dumb
    DEFAULT_MSG
    DUMB_LIBRARIES
    DUMB_INCLUDE_DIR
)

