INCLUDE(FindPackageHandleStandardArgs)

IF (NOT PORTMIDI_INCLUDE_DIR)
    IF (NOT PORTMIDI_INCLUDE_DIR_MIDI)
        FIND_PATH(PORTMIDI_INCLUDE_DIR_MIDI portmidi.h HINTS $ENV{PORTMIDI_DIR})
    ENDIF()

    IF (NOT PORTMIDI_INCLUDE_DIR_TIME)
        FIND_PATH(PORTMIDI_INCLUDE_DIR_TIME porttime.h HINTS $ENV{PORTMIDI_DIR})
    ENDIF()

    IF (PORTMIDI_INCLUDE_DIR_MIDI AND PORTMIDI_INCLUDE_DIR_TIME)
        SET(PORTMIDI_INCLUDE_DIR ${PORTMIDI_INCLUDE_DIR_MIDI})
        IF (NOT ${PORTMIDI_INCLUDE_DIR_MIDI} STREQUAL ${PORTMIDI_INCLUDE_DIR_TIME})
            SET(PORTMIDI_INCLUDE_DIR ${PORTMIDI_INCLUDE_DIR}
                                     ${PORTMIDI_INCLUDE_DIR_MIDI}
            )
        ENDIF()
    ENDIF()
ENDIF()

IF (NOT PORTMIDI_LIBRARIES)
    FIND_LIBRARY(PORTMIDI_LIBRARY portmidi HINTS $ENV{PORTMIDI_DIR})

    IF (PORTMIDI_LIBRARY)
        SET(PORTMIDI_LIBRARIES ${PORTMIDI_LIBRARY})
    ENDIF()
ENDIF()

MARK_AS_ADVANCED(PORTMIDI_INCLUDE_DIR)
MARK_AS_ADVANCED(PORTMIDI_INCLUDE_DIR_MIDI)
MARK_AS_ADVANCED(PORTMIDI_INCLUDE_DIR_TIME)
MARK_AS_ADVANCED(PORTMIDI_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    PortMidi
    DEFAULT_MSG
    PORTMIDI_LIBRARIES
    PORTMIDI_INCLUDE_DIR
)

